SHOW DATABASES; /*
+--------------------+
| Database           |
+--------------------+
| dars_demo          |
| information_schema |
| mashq              |
| mysql              |
| performance_schema |
| sys                |
+--------------------+
6 rows in set (0.00 sec)     */

USE `dars_demo`;    -- Database changed
SHOW TABLES;    /*
+----------------------+
| Tables_in_dars_demo  |
+----------------------+
| current_dept_emp     |
| departments          |
| dept_emp             |
| dept_emp_latest_date |
| dept_manager         |
| employees            |
| salaries             |
| titles               |
+----------------------+
8 rows in set (0.01 sec)    */

SELECT COUNT(*) FROM `employees`;   /* satr, qatorlar soni
+----------+
| COUNT(*) |
+----------+
|   300024 |
+----------+
1 row in set (0.03 sec) */

# DISTINCT - dublikatlarsiz ma'lumotlarni olish

SELECT DISTINCT `first_name`    -- first_name ustunidagi unikal qiymatlarni olish
FROM `employees`                -- employees jadvalidan
ORDER BY `first_name`;          -- ismlarni tartiblab chiqarish
/* jadvalni ko'rinishi:
+----------------+
| first_name     |
+----------------+
| Aamer          |
| Aamod          |
| Abdelaziz      |
| Abdelghani     |
| Abdelkader     |
| Abdelwaheb     |
| Abdulah        |
| Abdulla        |
| Achilleas      |
| Adam           |
| Adamantios     |
| Adas           |
| Adel           |
| Adhemar        |
| Adib           |
| Adil           |
| Adin           |
| Adit           |
| Adly           |
| Aemilian       |
| Aiichiro       |
| Aiman          |
| Aimee          |
| Akeel          |
| Akemi          |
| Akeno          |
| Akhilish       |
| Aksel          |
| Alagu          |
| Alain          |
| Alair          |
| Alassane       |
| Alejandra      |
| Alejandro      |
| Aleksandar     |
| Aleksander     |
| Alenka         |
| Alexius        |
| Almudena       |
| Alois          |
| Aloke          |
| Along          |
| Aloys          |
| Alper          |
| Alselm         |
| Aluzio         |
| Amabile        |
| Amalendu       |
| Amstein        |
| Anestis        |
| Angel          |
| Angus          |
| Anneke         |
| Anneli         |
| Annemarie      |
| Anoosh         |
| Anwar          |
| Anyuan         |
| Apostol        |
| Aral           |
| Aram           |
| Aran           |
| Arch           |
| Arco           |
| Arfst          |
| Aria           |
| Arie           |
| Arif           |
| Aris           |
| Arlette        |
| Armond         |
| Arnd           |
| Arne           |
| Arno           |
| Arnould        |
| Aron           |
| Arra           |
| Arto           |
| Arumugam       |
| Arun           |
| Aruna          |
| Arunachalam    |
| Arunas         |
| Arup           |
| Arve           |
| Arvin          |
| Arvind         |
| Ashish         |
| Atilio         |
| Atreye         |
| Atreyi         |
| Augustine      |
| Avishai        |
| Ayakannu       |
| Ayonca         |
| Babette        |
| Bader          |
| Badri          |
| Bangqing       |
| Baocai         |
| Baoqiu         |
| Barna          |
| Barry          |
| Bartek         |
| Barton         |
| Baruch         |
| Barun          |
| Basant         |
| Basem          |
| Basil          |
| Basim          |
| Baziley        |
| Becky          |
| Bedir          |
| Bedrich        |
| Behnaam        |
| Berhard        |
| Berna          |
| Bernardo       |
| Bernd          |
| Berni          |
| Bernice        |
| Bernt          |
| Berry          |
| Berthier       |
| Berto          |
| Beshir         |
| Bezalel        |
| Bikash         |
| Bilhanan       |
| Billie         |
| Billur         |
| Bingning       |
| Bluma          |
| Boalin         |
| Boaz           |
| Bodh           |
| Bodo           |
| Bogdan         |
| Boguslaw       |
| Bojan          |
| Bokyung        |
| Boriana        |
| Bouchung       |
| Boutros        |
| Bowen          |
| Branimir       |
| Breannda       |
| Brendon        |
| Brewster       |
| Brigham        |
| Byong          |
| Candida        |
| Candido        |
| Caolyn         |
| Carrsten       |
| Cathie         |
| Cedric         |
| Chaitali       |
| Chandrasekaran |
| Changho        |
| Chanjung       |
| Chaosheng      |
| Chaoyi         |
| Charlene       |
| Charmane       |
| Chenxi         |
| Chenye         |
| Chenyi         |
| Cheong         |
| Chikako        |
| Chikara        |
| Chinho         |
| Chinhyun       |
| Chinya         |
| Chiradeep      |
| Chiranjit      |
| Chirstian      |
| Chrisa         |
| Chriss         |
| Christ         |
| Christfried    |
| Christoper     |
| Christoph      |
| Christophe     |
| Chuanti        |
| Chuanyi        |
| Claude         |
| Claudi         |
| Clyde          |
| Collette       |
| Conal          |
| Conor          |
| Conrado        |
| Constantijn    |
| Constantine    |
| Constantino    |
| Cordelia       |
| Cristinel      |
| Cullen         |
| DAIDA          |
| Danae          |
| Danai          |
| Danco          |
| Danel          |
| Danil          |
| Danny          |
| Dannz          |
| Dante          |
| Dayanand       |
| Debaprosad     |
| Debatosh       |
| Deborah        |
| DeForest       |
| Dekang         |
| Demin          |
| Demos          |
| Denis          |
| Deniz          |
| Denny          |
| Dharmaraja     |
| Dhritiman      |
| Diederik       |
| Dietrich       |
| Dinah          |
| Dines          |
| Dinkar         |
| Dipankar       |
| Dipayan        |
| Divier         |
| Divine         |
| Djelloul       |
| Djenana        |
| Dmitri         |
| Dmitry         |
| Domenick       |
| Domenico       |
| Doohun         |
| Doowon         |
| Douadi         |
| Duangkaew      |
| Duke           |
| Dulce          |
| Dung           |
| Duri           |
| Duro           |
| Dzung          |
| Ebbe           |
| Eben           |
| Eberhardt      |
| Ebru           |
| Eckart         |
| Edwin          |
| Eirik          |
| Eishiro        |
| Ekawit         |
| Eldridge       |
| Elgin          |
| Elliott        |
| Elrique        |
| Elvia          |
| Elvis          |
| Elzbieta       |
| Emdad          |
| Emran          |
| Ennio          |
| Eran           |
| Erez           |
| Eric           |
| Erzsebet       |
| Etsuo          |
| Evgueni        |
| Ewing          |
| Fabrizio       |
| Fai            |
| Faiza          |
| Falguni        |
| Fan            |
| Fatemeh        |
| Fay            |
| Fayez          |
| Fei            |
| Feipei         |
| Feixiong       |
| Feiyu          |
| Felicidad      |
| Fen            |
| Ferdinand      |
| Filipe         |
| Filipp         |
| Flemming       |
| Florian        |
| Florina        |
| Foong          |
| Fox            |
| Francesca      |
| Francoise      |
| Franziska      |
| Frazer         |
| Frederique     |
| Freyja         |
| Froduald       |
| Fumiko         |
| Fumino         |
| Fumitaka       |
| Fumitake       |
| Fumiya         |
| Fumiyo         |
| Fun            |
| Fuqing         |
| Fusako         |
| Gad            |
| Gadiel         |
| Gaetan         |
| Gal            |
| Gao            |
| Garnet         |
| Garnik         |
| Gaurav         |
| Gay            |
| Gen            |
| Genevieve      |
| Genki          |
| Gennadi        |
| Gennady        |
| Genta          |
| Geoff          |
| Geoffrey       |
| Geoffry        |
| Georg          |
| George         |
| Georgi         |
| Georgy         |
| Ger            |
| Geraldo        |
| Gererd         |
| Ghassan        |
| Gian           |
| Gianluca       |
| Giao           |
| Giap           |
| Gift           |
| Gil            |
| Gila           |
| Gilbert        |
| Gill           |
| Gina           |
| Gino           |
| Gio            |
| Giordano       |
| Giri           |
| Girolamo       |
| Gita           |
| Gladys         |
| Goa            |
| Godehard       |
| Goetz          |
| Goh            |
| Golgen         |
| Goncalo        |
| Gonzalo        |
| Goo            |
| Gopalakrishnan |
| Gor            |
| Gou            |
| Greger         |
| Gregory        |
| Gretta         |
| Gritta         |
| Gro            |
| Guadalupe      |
| Guangming      |
| Gudjon         |
| Guenter        |
| Guiseppe       |
| Gully          |
| Gunilla        |
| Guoxiang       |
| Guozhong       |
| Gurbir         |
| Guther         |
| Guttorm        |
| Hailing        |
| Hairong        |
| Haldon         |
| Haldun         |
| Halsur         |
| Harjit         |
| Harngdar       |
| Hatem          |
| Hatim          |
| Hatsukazu      |
| Hauke          |
| Hausi          |
| Heather        |
| Heejo          |
| Heeju          |
| Heekeun        |
| Hein           |
| Heng           |
| Henk           |
| Heon           |
| Heping         |
| Herb           |
| Herbert        |
| Hercules       |
| Hidde          |
| Hidefumi       |
| Hidekazu       |
| Hideo          |
| Hideyuki       |
| Hilari         |
| Hilary         |
| Hinrich        |
| Hirochika      |
| Hironobu       |
| Hironoby       |
| Hiroyasu       |
| Hisao          |
| Hitofumi       |
| Hitomi         |
| Holgard        |
| Honesty        |
| Honglan        |
| Hongzhu        |
| Hongzue        |
| Horward        |
| Houman         |
| Howell         |
| Hsiangchu      |
| Huai           |
| Huan           |
| Huei           |
| Hugh           |
| Hugo           |
| Huican         |
| Huiqun         |
| Hyuckchul      |
| Hyuncheol      |
| Iara           |
| Ibibia         |
| Idoia          |
| IEEE           |
| Inderjeet      |
| Indrajit       |
| Ingemar        |
| Ingmar         |
| Insup          |
| Ioana          |
| Ipke           |
| Irena          |
| Irene          |
| Isaac          |
| Isamu          |
| Ishfaq         |
| Itzchak        |
| Izaskun        |
| Jaana          |
| Jaber          |
| Jackson        |
| Jacopo         |
| Jacqueline     |
| Jaewon         |
| Jaewoo         |
| Jagoda         |
| Jahangir       |
| Jaideep        |
| Jaihie         |
| Jamaludin      |
| Janalee        |
| Janche         |
| Jaques         |
| Jaroslava      |
| Jasminko       |
| Jayesh         |
| Jayson         |
| Jeane          |
| Jeanna         |
| Jeanne         |
| Jenwei         |
| Jeong          |
| Jessie         |
| Jiafu          |
| Jiakeng        |
| Jiang          |
| Jianhao        |
| Jianhua        |
| Jianhui        |
| Jiann          |
| Jianwen        |
| Jingling       |
| Jinpo          |
| Jinxi          |
| Jinya          |
| Jiong          |
| Jixiang        |
| JiYoung        |
| JoAnna         |
| JoAnne         |
| Jolita         |
| Jongsuk        |
| Jordanka       |
| Josyula        |
| Jouko          |
| Jouni          |
| Jovan          |
| Joydip         |
| Juichirou      |
| Jungsoon       |
| Junichi        |
| Junsik         |
| Juyoung        |
| Kagan          |
| Kaijung        |
| Kamakshi       |
| Kamran         |
| Kankanahalli   |
| Kannan         |
| Karlis         |
| Karoline       |
| Karsten        |
| Kasidit        |
| Kasturi        |
| Katsuo         |
| Katsuyuki      |
| Kauko          |
| KayLiang       |
| Kayoko         |
| Kazuhide       |
| Kazuhiko       |
| Kazuhira       |
| Kazuhiro       |
| Kazuhisa       |
| Kazuhito       |
| Kazunori       |
| Kazuyasu       |
| Keiichiro      |
| Kellie         |
| Kellyn         |
| Kendra         |
| Kenroku        |
| Kensei         |
| Kensyu         |
| Kenton         |
| Kerhong        |
| Kerryn         |
| Kersti         |
| Keung          |
| Khaled         |
| Khalid         |
| Khalil         |
| Khatoun        |
| Khedija        |
| Khoa           |
| Khosrow        |
| Khue           |
| Khun           |
| Kiam           |
| Kien           |
| King           |
| Kinh           |
| Kirk           |
| Kish           |
| Kitty          |
| Kiyokazu       |
| Kiyomitsu      |
| Kiyotoshi      |
| Koichi         |
| Kokou          |
| Kolar          |
| Koldo          |
| Kotesh         |
| Kousuke        |
| Krassimir      |
| Krisda         |
| Kristen        |
| Krister        |
| Kristian       |
| Kristin        |
| Kristina       |
| Kristine       |
| Kristinn       |
| Kristof        |
| Kshitij        |
| Kwan           |
| Kwangho        |
| Kwangjo        |
| Kwangsub       |
| Kwangyoen      |
| Kwee           |
| Kwok           |
| Kwun           |
| Kyoichi        |
| Lakshmi        |
| Lalit          |
| Lansing        |
| Larisa         |
| Laurentiu      |
| Leaf           |
| Leah           |
| Leandro        |
| Lech           |
| Leen           |
| Leif           |
| Lein           |
| Lena           |
| Lene           |
| Leni           |
| Lenore         |
| Leon           |
| Leszek         |
| Leucio         |
| Licheng        |
| Lidong         |
| Lihong         |
| Lijia          |
| Lijie          |
| Lillian        |
| LiMin          |
| Limsoon        |
| Lobel          |
| Lokesh         |
| Lorien         |
| Lubomir        |
| Lucian         |
| Lucien         |
| Luerbio        |
| Luigi          |
| Luisa          |
| Luise          |
| Lunjin         |
| Mabhin         |
| Mabo           |
| Mabry          |
| Macha          |
| Mack           |
| Mads           |
| Magdalena      |
| Magy           |
| Maha           |
| Mahendra       |
| Mahmut         |
| Maia           |
| Maik           |
| Maja           |
| Makato         |
| Make           |
| Malu           |
| Mamdouh        |
| Mana           |
| Mandell        |
| Mang           |
| Mani           |
| Manibrata      |
| Manohar        |
| Mansur         |
| Mantis         |
| Manton         |
| Manu           |
| Mara           |
| Marc           |
| Marco          |
| Marek          |
| Maren          |
| Margareta      |
| Margo          |
| Mari           |
| Maria          |
| Mariangiola    |
| Marie          |
| Marin          |
| Mario          |
| Maris          |
| Marit          |
| Mariusz        |
| Marjo          |
| Mark           |
| Marke          |
| Marko          |
| Marl           |
| Marla          |
| Marlo          |
| Marsal         |
| Marsha         |
| Marsja         |
| Mart           |
| Martial        |
| Martien        |
| Martijn        |
| Martina        |
| Martine        |
| Martins        |
| Mary           |
| Masadi         |
| Masaki         |
| Masako         |
| Masali         |
| Masami         |
| Masamitsu      |
| Masanao        |
| Masaru         |
| Masasuke       |
| Masato         |
| Masoud         |
| Matk           |
| Mats           |
| Matt           |
| Maya           |
| Mayuko         |
| Mayumi         |
| Mayuri         |
| Mechthild      |
| Menkae         |
| Michaela       |
| Mihalis        |
| Mikhail        |
| Mingdong       |
| Minghong       |
| Mingsen        |
| Mingzeng       |
| Miomir         |
| Miquel         |
| Mircea         |
| Mitchel        |
| Mitsuyuki      |
| Miyeon         |
| Mizuhito       |
| Mohamadou      |
| Mohammad       |
| Mohammed       |
| Mohan          |
| Mohd           |
| Moheb          |
| Mohit          |
| Mohua          |
| Moie           |
| Mokhtar        |
| Mona           |
| Mong           |
| Moni           |
| Monique        |
| Mooi           |
| Moon           |
| Mori           |
| Moriyoshi      |
| Morrie         |
| Morris         |
| Moss           |
| Mostafa        |
| Moti           |
| Moto           |
| Mototsugu      |
| Moty           |
| Mountaz        |
| Mrinalini      |
| Munehiko       |
| Munehiro       |
| Munenori       |
| Muneo          |
| Munir          |
| Murthy         |
| Muzhong        |
| Nadjib         |
| Naftali        |
| Naftaly        |
| Nagui          |
| Nahid          |
| Nahla          |
| Nahum          |
| Nakhoon        |
| Nalini         |
| Naraig         |
| Narain         |
| Nathalie       |
| Nathan         |
| Navid          |
| Navin          |
| Nechama        |
| Nectarios      |
| Neelam         |
| Neven          |
| Nevin          |
| Nevio          |
| Niclas         |
| Nidapan        |
| Nigel          |
| Nikolaos       |
| Nikolaus       |
| Nimmagadda     |
| Niranjan       |
| Nirmal         |
| Nishit         |
| Niteen         |
| Nitsan         |
| Nobuyoshi      |
| Noritoshi      |
| Oddvar         |
| Odinaldo       |
| Odoardo        |
| Odysseas       |
| Oguz           |
| Ohad           |
| Oksana         |
| Oldrich        |
| Olivera        |
| Ortrud         |
| Ortrun         |
| Oscal          |
| Oscar          |
| Otilia         |
| Otmar          |
| Ottavia        |
| Owen           |
| Paddy          |
| Padma          |
| Palash         |
| Paloma         |
| Panayotis      |
| Pantung        |
| Paraskevi      |
| Paris          |
| Parke          |
| Parto          |
| Parviz         |
| Pascal         |
| Pasqua         |
| Patricia       |
| Patricio       |
| Peer           |
| Percy          |
| Perla          |
| Perry          |
| Persi          |
| Peternela      |
| Petter         |
| Phillip        |
| Phule          |
| Phuoc          |
| Pintsang       |
| Piyawadee      |
| Piyush         |
| Pohua          |
| Poorav         |
| Poornachandra  |
| Pradeep        |
| Pragnesh       |
| Pramod         |
| Pranas         |
| Pranav         |
| Pranay         |
| Pranjal        |
| Prasadram      |
| Premal         |
| Premsyl        |
| Prodip         |
| Przemyslawa    |
| Qingxiang      |
| Qiwen          |
| Quingbo        |
| Qunsheng       |
| Radhakrishnan  |
| Radhia         |
| Radhika        |
| Radoslaw       |
| Rafael         |
| Rafail         |
| Rafols         |
| Raimond        |
| Rajmohan       |
| Ramachenga     |
| Ramalingam     |
| Ramya          |
| Ramzi          |
| Ranan          |
| Rance          |
| Randi          |
| Randy          |
| Ranga          |
| Rasiah         |
| Rasikan        |
| Ravishankar    |
| Rayond         |
| Reinhard       |
| Reinhold       |
| Remco          |
| Remko          |
| Remmert        |
| Remzi          |
| Renee          |
| Renny          |
| Reuven         |
| Richara        |
| Richard        |
| Rildo          |
| Rimli          |
| Rimon          |
| Roddy          |
| Roded          |
| Ronghao        |
| Ronnie         |
| Rosalie        |
| Rosalyn        |
| Rosella        |
| Roselyn        |
| Rosine         |
| Rosita         |
| Rosli          |
| Rutger         |
| Sachar         |
| Sachem         |
| Sachin         |
| Sachio         |
| Saddek         |
| Sadegh         |
| Sadok          |
| Sadun          |
| Saeed          |
| Saeko          |
| Sahrah         |
| Sailaja        |
| Sajjad         |
| Sajjan         |
| Sakthirel      |
| Salvador       |
| Sampalli       |
| Samphel        |
| Sandeepan      |
| Sangeeta       |
| Saniya         |
| Sanjai         |
| Sanjay         |
| Sanjeeva       |
| Sanjit         |
| Sanjiv         |
| Sanjoy         |
| Sariel         |
| Sarita         |
| Sasan          |
| Sashi          |
| Sastry         |
| Satoru         |
| Satosi         |
| Satyanarayana  |
| Sedat          |
| Selwyn         |
| Seongbae       |
| Seongbin       |
| Serap          |
| Serenella      |
| Serge          |
| Sergi          |
| Serif          |
| Seshu          |
| Shahab         |
| Shahaf         |
| Shahar         |
| Shahid         |
| Shai           |
| Shaibal        |
| Shakhar        |
| Shaleah        |
| Shalesh        |
| Sham           |
| Shan           |
| Shao           |
| Shaowei        |
| Shaowen        |
| Shaunak        |
| Shaw           |
| Shawna         |
| Shay           |
| Shaz           |
| Shem           |
| Shen           |
| Shichao        |
| Shietung       |
| Shigeaki       |
| Shigehiro      |
| Shigehito      |
| Shigeichiro    |
| Shigenori      |
| Shigeo         |
| Shigeu         |
| Shih           |
| Shim           |
| Shimshon       |
| Shin           |
| Shir           |
| Shirish        |
| Shiv           |
| Shmuel         |
| Shooichi       |
| Shounak        |
| Shridhar       |
| Shrikanth      |
| Shugo          |
| Shuho          |
| Shuichi        |
| Shuji          |
| Shuky          |
| Shunichi       |
| Shushma        |
| Shuzo          |
| Siamak         |
| Sibyl          |
| Siddarth       |
| Sigeru         |
| Sivanarayana   |
| Slavian        |
| Snehasis       |
| Soenke         |
| Somnath        |
| Sorina         |
| Souichi        |
| Spyrose        |
| Sreekrishna    |
| Sreenivas      |
| Srinidhi       |
| Stabislas      |
| Stafford       |
| Stamatina      |
| Steen          |
| Stein          |
| Stella         |
| Stepehn        |
| Steve          |
| Stevo          |
| Subbu          |
| Subhada        |
| Subhankar      |
| Subhash        |
| Subhrajyoti    |
| Subir          |
| Sudhanshu      |
| Sudharsan      |
| Suebskul       |
| Sugwoo         |
| Sukumar        |
| Sumali         |
| Sumant         |
| Sungwon        |
| Supot          |
| Surveyors      |
| Susanna        |
| Susanne        |
| Susanta        |
| Sushant        |
| Susuma         |
| Susumu         |
| Suvo           |
| Suzette        |
| Sven           |
| Sverrir        |
| Syozo          |
| Szabolcs       |
| Tadahiko       |
| Tadahiro       |
| Tadanori       |
| Taegyun        |
| Taiji          |
| Taisook        |
| Taizo          |
| Takahira       |
| Takahiro       |
| Takahito       |
| Takanari       |
| Takushi        |
| Tamiya         |
| Tayeb          |
| Teiji          |
| Temple         |
| Terresa        |
| Teruyuki       |
| Tesuro         |
| Tesuya         |
| Tetsurou       |
| Tetsushi       |
| Teunis         |
| Thanasis       |
| Theirry        |
| Theron         |
| Thodoros       |
| Tianruo        |
| Tiina          |
| Tokuyasu       |
| Tommaso        |
| Tomofumi       |
| Tomokazu       |
| Tomoyuki       |
| Toney          |
| Tonia          |
| Tonny          |
| Toong          |
| Tooru          |
| Torsten        |
| Toshiki        |
| Toshiko        |
| Toshimi        |
| Toshimitsu     |
| Toshimo        |
| Toshimori      |
| Tran           |
| Tremaine       |
| Tristan        |
| Troy           |
| Tru            |
| True           |
| Trygve         |
| Tse            |
| Tsuneo         |
| Tsutomu        |
| Tsvetan        |
| Tsz            |
| Tua            |
| Turgut         |
| Tuval          |
| Tze            |
| Tzu            |
| Tzvetan        |
| Udaiprakash    |
| Udi            |
| Udo            |
| Ugo            |
| Uinam          |
| Ulf            |
| Uli            |
| Ulises         |
| Ult            |
| Uma            |
| Unal           |
| Ung            |
| Uno            |
| Uri            |
| Uriel          |
| Urs            |
| Uta            |
| Ute            |
| Utpal          |
| Utz            |
| Uwe            |
| Uzi            |
| Val            |
| Valdiodio      |
| Valeri         |
| Valery         |
| Valeska        |
| Valter         |
| Van            |
| Vasilii        |
| Vasilis        |
| Vasiliy        |
| Vatsa          |
| Venkatesan     |
| Vesna          |
| Vidar          |
| Vidya          |
| Vincent        |
| Vishu          |
| Vishv          |
| Vishwani       |
| Visit          |
| Vitali         |
| Vitaly         |
| Vivian         |
| Vojin          |
| Volkmar        |
| Vugranam       |
| Waiman         |
| Wanqing        |
| Wayne          |
| Weicheng       |
| Weidon         |
| Weijing        |
| Weiru          |
| Weiwu          |
| Weiye          |
| Weiyi          |
| Werner         |
| Willard        |
| Wilmer         |
| Wojceich       |
| Wonhee         |
| Woody          |
| Wuxu           |
| Xiadong        |
| Xiahua         |
| Xianlong       |
| Xiaobin        |
| Xiaocheng      |
| Xiaoheng       |
| Xiaopeng       |
| Xiaoqiang      |
| Xiaoqiu        |
| Xiaoshan       |
| Xinan          |
| Xinglin        |
| Xinyu          |
| Xiong          |
| Xiping         |
| Xudong         |
| Xuedong        |
| Xuejia         |
| Xuejun         |
| Xumin          |
| Yaghout        |
| Yagil          |
| Yahiko         |
| Yakichi        |
| Yakkov         |
| Yannik         |
| Yannis         |
| Yechezkel      |
| Yechiam        |
| Yefim          |
| Yifei          |
| Yinghua        |
| Yinlin         |
| Yishai         |
| Yishay         |
| Ymte           |
| Yolla          |
| Yongdong       |
| Yonghoan       |
| Yonghong       |
| Yongmao        |
| Yongmin        |
| Yongqiao       |
| Yoshimitsu     |
| Yoshinari      |
| Youjian        |
| Youngkon       |
| Younwoo        |
| Youpyo         |
| Youssef        |
| Yucai          |
| Yucel          |
| Yuchang        |
| Yuguang        |
| Yuichiro       |
| Yunming        |
| Yuping         |
| Yuqun          |
| Yurii          |
| Yurij          |
| Yuriy          |
| Yuuichi        |
| Zdislav        |
| Zejun          |
| Zeljko         |
| Zengping       |
| Zeydy          |
| Zhanqiu        |
| Zhaofang       |
| Zhenbing       |
| Zhenhua        |
| Zhensheng      |
| Zhigen         |
| Zhiguo         |
| Zhilian        |
| Zhiwei         |
| Zhonghua       |
| Zhonghui       |
| Zhongwei       |
| Zijian         |
| Zine           |
| Zissis         |
| Zita           |
| Zito           |
| Ziva           |
| Ziya           |
| Ziyad          |
| Zongyan        |
| Zorica         |
| Zsolt          |
| Zvonko         |
+----------------+
1275 rows in set (0.29 sec) */

SELECT COUNT(DISTINCT `first_name`)
FROM `employees`;   /*
+------------------------------+
| COUNT(DISTINCT `first_name`) |
+------------------------------+
|                         1275 |
+------------------------------+
1 row in set (0.23 sec) */

#         GROUP BY  - Guruhlash
# GROUP BY - ko'proq SUM(), AVG(), MAX(), MIN() va COUNT() funksiyalari bilan ishlatiladi.
SELECT `first_name`     -- first_name ustuni tanlanib
FROM `employees`        -- employees jadvalidan
GROUP BY `first_name`   -- ismi bo'yicha guruhlansin
ORDER BY `first_name`;  /* natija:
+----------------+
| first_name     |
+----------------+
| Aamer          |
| Aamod          |
| Abdelaziz      |
| Abdelghani     |
| Abdelkader     |
| Abdelwaheb     |
| Abdulah        |
| Abdulla        |
| Achilleas      |
| Adam           |
| Adamantios     |
| Adas           |
| Adel           |
| Adhemar        |
| Adib           |
| Adil           |
| Adin           |
| Adit           |
| Adly           |
| Aemilian       |
| Aiichiro       |
| Aiman          |
| Aimee          |
| Akeel          |
| Akemi          |
| Akeno          |
| Akhilish       |
| Aksel          |
| Alagu          |
| Alain          |
| Alair          |
| Alassane       |
| Alejandra      |
| Alejandro      |
| Aleksandar     |
| Aleksander     |
| Alenka         |
| Alexius        |
| Almudena       |
| Alois          |
| Aloke          |
| Along          |
| Aloys          |
| Alper          |
| Alselm         |
| Aluzio         |
| Amabile        |
| Amalendu       |
| Amstein        |
| Anestis        |
| Angel          |
| Angus          |
| Anneke         |
| Anneli         |
| Annemarie      |
| Anoosh         |
| Anwar          |
| Anyuan         |
| Apostol        |
| Aral           |
| Aram           |
| Aran           |
| Arch           |
| Arco           |
| Arfst          |
| Aria           |
| Arie           |
| Arif           |
| Aris           |
| Arlette        |
| Armond         |
| Arnd           |
| Arne           |
| Arno           |
| Arnould        |
| Aron           |
| Arra           |
| Arto           |
| Arumugam       |
| Arun           |
| Aruna          |
| Arunachalam    |
| Arunas         |
| Arup           |
| Arve           |
| Arvin          |
| Arvind         |
| Ashish         |
| Atilio         |
| Atreye         |
| Atreyi         |
| Augustine      |
| Avishai        |
| Ayakannu       |
| Ayonca         |
| Babette        |
| Bader          |
| Badri          |
| Bangqing       |
| Baocai         |
| Baoqiu         |
| Barna          |
| Barry          |
| Bartek         |
| Barton         |
| Baruch         |
| Barun          |
| Basant         |
| Basem          |
| Basil          |
| Basim          |
| Baziley        |
| Becky          |
| Bedir          |
| Bedrich        |
| Behnaam        |
| Berhard        |
| Berna          |
| Bernardo       |
| Bernd          |
| Berni          |
| Bernice        |
| Bernt          |
| Berry          |
| Berthier       |
| Berto          |
| Beshir         |
| Bezalel        |
| Bikash         |
| Bilhanan       |
| Billie         |
| Billur         |
| Bingning       |
| Bluma          |
| Boalin         |
| Boaz           |
| Bodh           |
| Bodo           |
| Bogdan         |
| Boguslaw       |
| Bojan          |
| Bokyung        |
| Boriana        |
| Bouchung       |
| Boutros        |
| Bowen          |
| Branimir       |
| Breannda       |
| Brendon        |
| Brewster       |
| Brigham        |
| Byong          |
| Candida        |
| Candido        |
| Caolyn         |
| Carrsten       |
| Cathie         |
| Cedric         |
| Chaitali       |
| Chandrasekaran |
| Changho        |
| Chanjung       |
| Chaosheng      |
| Chaoyi         |
| Charlene       |
| Charmane       |
| Chenxi         |
| Chenye         |
| Chenyi         |
| Cheong         |
| Chikako        |
| Chikara        |
| Chinho         |
| Chinhyun       |
| Chinya         |
| Chiradeep      |
| Chiranjit      |
| Chirstian      |
| Chrisa         |
| Chriss         |
| Christ         |
| Christfried    |
| Christoper     |
| Christoph      |
| Christophe     |
| Chuanti        |
| Chuanyi        |
| Claude         |
| Claudi         |
| Clyde          |
| Collette       |
| Conal          |
| Conor          |
| Conrado        |
| Constantijn    |
| Constantine    |
| Constantino    |
| Cordelia       |
| Cristinel      |
| Cullen         |
| DAIDA          |
| Danae          |
| Danai          |
| Danco          |
| Danel          |
| Danil          |
| Danny          |
| Dannz          |
| Dante          |
| Dayanand       |
| Debaprosad     |
| Debatosh       |
| Deborah        |
| DeForest       |
| Dekang         |
| Demin          |
| Demos          |
| Denis          |
| Deniz          |
| Denny          |
| Dharmaraja     |
| Dhritiman      |
| Diederik       |
| Dietrich       |
| Dinah          |
| Dines          |
| Dinkar         |
| Dipankar       |
| Dipayan        |
| Divier         |
| Divine         |
| Djelloul       |
| Djenana        |
| Dmitri         |
| Dmitry         |
| Domenick       |
| Domenico       |
| Doohun         |
| Doowon         |
| Douadi         |
| Duangkaew      |
| Duke           |
| Dulce          |
| Dung           |
| Duri           |
| Duro           |
| Dzung          |
| Ebbe           |
| Eben           |
| Eberhardt      |
| Ebru           |
| Eckart         |
| Edwin          |
| Eirik          |
| Eishiro        |
| Ekawit         |
| Eldridge       |
| Elgin          |
| Elliott        |
| Elrique        |
| Elvia          |
| Elvis          |
| Elzbieta       |
| Emdad          |
| Emran          |
| Ennio          |
| Eran           |
| Erez           |
| Eric           |
| Erzsebet       |
| Etsuo          |
| Evgueni        |
| Ewing          |
| Fabrizio       |
| Fai            |
| Faiza          |
| Falguni        |
| Fan            |
| Fatemeh        |
| Fay            |
| Fayez          |
| Fei            |
| Feipei         |
| Feixiong       |
| Feiyu          |
| Felicidad      |
| Fen            |
| Ferdinand      |
| Filipe         |
| Filipp         |
| Flemming       |
| Florian        |
| Florina        |
| Foong          |
| Fox            |
| Francesca      |
| Francoise      |
| Franziska      |
| Frazer         |
| Frederique     |
| Freyja         |
| Froduald       |
| Fumiko         |
| Fumino         |
| Fumitaka       |
| Fumitake       |
| Fumiya         |
| Fumiyo         |
| Fun            |
| Fuqing         |
| Fusako         |
| Gad            |
| Gadiel         |
| Gaetan         |
| Gal            |
| Gao            |
| Garnet         |
| Garnik         |
| Gaurav         |
| Gay            |
| Gen            |
| Genevieve      |
| Genki          |
| Gennadi        |
| Gennady        |
| Genta          |
| Geoff          |
| Geoffrey       |
| Geoffry        |
| Georg          |
| George         |
| Georgi         |
| Georgy         |
| Ger            |
| Geraldo        |
| Gererd         |
| Ghassan        |
| Gian           |
| Gianluca       |
| Giao           |
| Giap           |
| Gift           |
| Gil            |
| Gila           |
| Gilbert        |
| Gill           |
| Gina           |
| Gino           |
| Gio            |
| Giordano       |
| Giri           |
| Girolamo       |
| Gita           |
| Gladys         |
| Goa            |
| Godehard       |
| Goetz          |
| Goh            |
| Golgen         |
| Goncalo        |
| Gonzalo        |
| Goo            |
| Gopalakrishnan |
| Gor            |
| Gou            |
| Greger         |
| Gregory        |
| Gretta         |
| Gritta         |
| Gro            |
| Guadalupe      |
| Guangming      |
| Gudjon         |
| Guenter        |
| Guiseppe       |
| Gully          |
| Gunilla        |
| Guoxiang       |
| Guozhong       |
| Gurbir         |
| Guther         |
| Guttorm        |
| Hailing        |
| Hairong        |
| Haldon         |
| Haldun         |
| Halsur         |
| Harjit         |
| Harngdar       |
| Hatem          |
| Hatim          |
| Hatsukazu      |
| Hauke          |
| Hausi          |
| Heather        |
| Heejo          |
| Heeju          |
| Heekeun        |
| Hein           |
| Heng           |
| Henk           |
| Heon           |
| Heping         |
| Herb           |
| Herbert        |
| Hercules       |
| Hidde          |
| Hidefumi       |
| Hidekazu       |
| Hideo          |
| Hideyuki       |
| Hilari         |
| Hilary         |
| Hinrich        |
| Hirochika      |
| Hironobu       |
| Hironoby       |
| Hiroyasu       |
| Hisao          |
| Hitofumi       |
| Hitomi         |
| Holgard        |
| Honesty        |
| Honglan        |
| Hongzhu        |
| Hongzue        |
| Horward        |
| Houman         |
| Howell         |
| Hsiangchu      |
| Huai           |
| Huan           |
| Huei           |
| Hugh           |
| Hugo           |
| Huican         |
| Huiqun         |
| Hyuckchul      |
| Hyuncheol      |
| Iara           |
| Ibibia         |
| Idoia          |
| IEEE           |
| Inderjeet      |
| Indrajit       |
| Ingemar        |
| Ingmar         |
| Insup          |
| Ioana          |
| Ipke           |
| Irena          |
| Irene          |
| Isaac          |
| Isamu          |
| Ishfaq         |
| Itzchak        |
| Izaskun        |
| Jaana          |
| Jaber          |
| Jackson        |
| Jacopo         |
| Jacqueline     |
| Jaewon         |
| Jaewoo         |
| Jagoda         |
| Jahangir       |
| Jaideep        |
| Jaihie         |
| Jamaludin      |
| Janalee        |
| Janche         |
| Jaques         |
| Jaroslava      |
| Jasminko       |
| Jayesh         |
| Jayson         |
| Jeane          |
| Jeanna         |
| Jeanne         |
| Jenwei         |
| Jeong          |
| Jessie         |
| Jiafu          |
| Jiakeng        |
| Jiang          |
| Jianhao        |
| Jianhua        |
| Jianhui        |
| Jiann          |
| Jianwen        |
| Jingling       |
| Jinpo          |
| Jinxi          |
| Jinya          |
| Jiong          |
| Jixiang        |
| JiYoung        |
| JoAnna         |
| JoAnne         |
| Jolita         |
| Jongsuk        |
| Jordanka       |
| Josyula        |
| Jouko          |
| Jouni          |
| Jovan          |
| Joydip         |
| Juichirou      |
| Jungsoon       |
| Junichi        |
| Junsik         |
| Juyoung        |
| Kagan          |
| Kaijung        |
| Kamakshi       |
| Kamran         |
| Kankanahalli   |
| Kannan         |
| Karlis         |
| Karoline       |
| Karsten        |
| Kasidit        |
| Kasturi        |
| Katsuo         |
| Katsuyuki      |
| Kauko          |
| KayLiang       |
| Kayoko         |
| Kazuhide       |
| Kazuhiko       |
| Kazuhira       |
| Kazuhiro       |
| Kazuhisa       |
| Kazuhito       |
| Kazunori       |
| Kazuyasu       |
| Keiichiro      |
| Kellie         |
| Kellyn         |
| Kendra         |
| Kenroku        |
| Kensei         |
| Kensyu         |
| Kenton         |
| Kerhong        |
| Kerryn         |
| Kersti         |
| Keung          |
| Khaled         |
| Khalid         |
| Khalil         |
| Khatoun        |
| Khedija        |
| Khoa           |
| Khosrow        |
| Khue           |
| Khun           |
| Kiam           |
| Kien           |
| King           |
| Kinh           |
| Kirk           |
| Kish           |
| Kitty          |
| Kiyokazu       |
| Kiyomitsu      |
| Kiyotoshi      |
| Koichi         |
| Kokou          |
| Kolar          |
| Koldo          |
| Kotesh         |
| Kousuke        |
| Krassimir      |
| Krisda         |
| Kristen        |
| Krister        |
| Kristian       |
| Kristin        |
| Kristina       |
| Kristine       |
| Kristinn       |
| Kristof        |
| Kshitij        |
| Kwan           |
| Kwangho        |
| Kwangjo        |
| Kwangsub       |
| Kwangyoen      |
| Kwee           |
| Kwok           |
| Kwun           |
| Kyoichi        |
| Lakshmi        |
| Lalit          |
| Lansing        |
| Larisa         |
| Laurentiu      |
| Leaf           |
| Leah           |
| Leandro        |
| Lech           |
| Leen           |
| Leif           |
| Lein           |
| Lena           |
| Lene           |
| Leni           |
| Lenore         |
| Leon           |
| Leszek         |
| Leucio         |
| Licheng        |
| Lidong         |
| Lihong         |
| Lijia          |
| Lijie          |
| Lillian        |
| LiMin          |
| Limsoon        |
| Lobel          |
| Lokesh         |
| Lorien         |
| Lubomir        |
| Lucian         |
| Lucien         |
| Luerbio        |
| Luigi          |
| Luisa          |
| Luise          |
| Lunjin         |
| Mabhin         |
| Mabo           |
| Mabry          |
| Macha          |
| Mack           |
| Mads           |
| Magdalena      |
| Magy           |
| Maha           |
| Mahendra       |
| Mahmut         |
| Maia           |
| Maik           |
| Maja           |
| Makato         |
| Make           |
| Malu           |
| Mamdouh        |
| Mana           |
| Mandell        |
| Mang           |
| Mani           |
| Manibrata      |
| Manohar        |
| Mansur         |
| Mantis         |
| Manton         |
| Manu           |
| Mara           |
| Marc           |
| Marco          |
| Marek          |
| Maren          |
| Margareta      |
| Margo          |
| Mari           |
| Maria          |
| Mariangiola    |
| Marie          |
| Marin          |
| Mario          |
| Maris          |
| Marit          |
| Mariusz        |
| Marjo          |
| Mark           |
| Marke          |
| Marko          |
| Marl           |
| Marla          |
| Marlo          |
| Marsal         |
| Marsha         |
| Marsja         |
| Mart           |
| Martial        |
| Martien        |
| Martijn        |
| Martina        |
| Martine        |
| Martins        |
| Mary           |
| Masadi         |
| Masaki         |
| Masako         |
| Masali         |
| Masami         |
| Masamitsu      |
| Masanao        |
| Masaru         |
| Masasuke       |
| Masato         |
| Masoud         |
| Matk           |
| Mats           |
| Matt           |
| Maya           |
| Mayuko         |
| Mayumi         |
| Mayuri         |
| Mechthild      |
| Menkae         |
| Michaela       |
| Mihalis        |
| Mikhail        |
| Mingdong       |
| Minghong       |
| Mingsen        |
| Mingzeng       |
| Miomir         |
| Miquel         |
| Mircea         |
| Mitchel        |
| Mitsuyuki      |
| Miyeon         |
| Mizuhito       |
| Mohamadou      |
| Mohammad       |
| Mohammed       |
| Mohan          |
| Mohd           |
| Moheb          |
| Mohit          |
| Mohua          |
| Moie           |
| Mokhtar        |
| Mona           |
| Mong           |
| Moni           |
| Monique        |
| Mooi           |
| Moon           |
| Mori           |
| Moriyoshi      |
| Morrie         |
| Morris         |
| Moss           |
| Mostafa        |
| Moti           |
| Moto           |
| Mototsugu      |
| Moty           |
| Mountaz        |
| Mrinalini      |
| Munehiko       |
| Munehiro       |
| Munenori       |
| Muneo          |
| Munir          |
| Murthy         |
| Muzhong        |
| Nadjib         |
| Naftali        |
| Naftaly        |
| Nagui          |
| Nahid          |
| Nahla          |
| Nahum          |
| Nakhoon        |
| Nalini         |
| Naraig         |
| Narain         |
| Nathalie       |
| Nathan         |
| Navid          |
| Navin          |
| Nechama        |
| Nectarios      |
| Neelam         |
| Neven          |
| Nevin          |
| Nevio          |
| Niclas         |
| Nidapan        |
| Nigel          |
| Nikolaos       |
| Nikolaus       |
| Nimmagadda     |
| Niranjan       |
| Nirmal         |
| Nishit         |
| Niteen         |
| Nitsan         |
| Nobuyoshi      |
| Noritoshi      |
| Oddvar         |
| Odinaldo       |
| Odoardo        |
| Odysseas       |
| Oguz           |
| Ohad           |
| Oksana         |
| Oldrich        |
| Olivera        |
| Ortrud         |
| Ortrun         |
| Oscal          |
| Oscar          |
| Otilia         |
| Otmar          |
| Ottavia        |
| Owen           |
| Paddy          |
| Padma          |
| Palash         |
| Paloma         |
| Panayotis      |
| Pantung        |
| Paraskevi      |
| Paris          |
| Parke          |
| Parto          |
| Parviz         |
| Pascal         |
| Pasqua         |
| Patricia       |
| Patricio       |
| Peer           |
| Percy          |
| Perla          |
| Perry          |
| Persi          |
| Peternela      |
| Petter         |
| Phillip        |
| Phule          |
| Phuoc          |
| Pintsang       |
| Piyawadee      |
| Piyush         |
| Pohua          |
| Poorav         |
| Poornachandra  |
| Pradeep        |
| Pragnesh       |
| Pramod         |
| Pranas         |
| Pranav         |
| Pranay         |
| Pranjal        |
| Prasadram      |
| Premal         |
| Premsyl        |
| Prodip         |
| Przemyslawa    |
| Qingxiang      |
| Qiwen          |
| Quingbo        |
| Qunsheng       |
| Radhakrishnan  |
| Radhia         |
| Radhika        |
| Radoslaw       |
| Rafael         |
| Rafail         |
| Rafols         |
| Raimond        |
| Rajmohan       |
| Ramachenga     |
| Ramalingam     |
| Ramya          |
| Ramzi          |
| Ranan          |
| Rance          |
| Randi          |
| Randy          |
| Ranga          |
| Rasiah         |
| Rasikan        |
| Ravishankar    |
| Rayond         |
| Reinhard       |
| Reinhold       |
| Remco          |
| Remko          |
| Remmert        |
| Remzi          |
| Renee          |
| Renny          |
| Reuven         |
| Richara        |
| Richard        |
| Rildo          |
| Rimli          |
| Rimon          |
| Roddy          |
| Roded          |
| Ronghao        |
| Ronnie         |
| Rosalie        |
| Rosalyn        |
| Rosella        |
| Roselyn        |
| Rosine         |
| Rosita         |
| Rosli          |
| Rutger         |
| Sachar         |
| Sachem         |
| Sachin         |
| Sachio         |
| Saddek         |
| Sadegh         |
| Sadok          |
| Sadun          |
| Saeed          |
| Saeko          |
| Sahrah         |
| Sailaja        |
| Sajjad         |
| Sajjan         |
| Sakthirel      |
| Salvador       |
| Sampalli       |
| Samphel        |
| Sandeepan      |
| Sangeeta       |
| Saniya         |
| Sanjai         |
| Sanjay         |
| Sanjeeva       |
| Sanjit         |
| Sanjiv         |
| Sanjoy         |
| Sariel         |
| Sarita         |
| Sasan          |
| Sashi          |
| Sastry         |
| Satoru         |
| Satosi         |
| Satyanarayana  |
| Sedat          |
| Selwyn         |
| Seongbae       |
| Seongbin       |
| Serap          |
| Serenella      |
| Serge          |
| Sergi          |
| Serif          |
| Seshu          |
| Shahab         |
| Shahaf         |
| Shahar         |
| Shahid         |
| Shai           |
| Shaibal        |
| Shakhar        |
| Shaleah        |
| Shalesh        |
| Sham           |
| Shan           |
| Shao           |
| Shaowei        |
| Shaowen        |
| Shaunak        |
| Shaw           |
| Shawna         |
| Shay           |
| Shaz           |
| Shem           |
| Shen           |
| Shichao        |
| Shietung       |
| Shigeaki       |
| Shigehiro      |
| Shigehito      |
| Shigeichiro    |
| Shigenori      |
| Shigeo         |
| Shigeu         |
| Shih           |
| Shim           |
| Shimshon       |
| Shin           |
| Shir           |
| Shirish        |
| Shiv           |
| Shmuel         |
| Shooichi       |
| Shounak        |
| Shridhar       |
| Shrikanth      |
| Shugo          |
| Shuho          |
| Shuichi        |
| Shuji          |
| Shuky          |
| Shunichi       |
| Shushma        |
| Shuzo          |
| Siamak         |
| Sibyl          |
| Siddarth       |
| Sigeru         |
| Sivanarayana   |
| Slavian        |
| Snehasis       |
| Soenke         |
| Somnath        |
| Sorina         |
| Souichi        |
| Spyrose        |
| Sreekrishna    |
| Sreenivas      |
| Srinidhi       |
| Stabislas      |
| Stafford       |
| Stamatina      |
| Steen          |
| Stein          |
| Stella         |
| Stepehn        |
| Steve          |
| Stevo          |
| Subbu          |
| Subhada        |
| Subhankar      |
| Subhash        |
| Subhrajyoti    |
| Subir          |
| Sudhanshu      |
| Sudharsan      |
| Suebskul       |
| Sugwoo         |
| Sukumar        |
| Sumali         |
| Sumant         |
| Sungwon        |
| Supot          |
| Surveyors      |
| Susanna        |
| Susanne        |
| Susanta        |
| Sushant        |
| Susuma         |
| Susumu         |
| Suvo           |
| Suzette        |
| Sven           |
| Sverrir        |
| Syozo          |
| Szabolcs       |
| Tadahiko       |
| Tadahiro       |
| Tadanori       |
| Taegyun        |
| Taiji          |
| Taisook        |
| Taizo          |
| Takahira       |
| Takahiro       |
| Takahito       |
| Takanari       |
| Takushi        |
| Tamiya         |
| Tayeb          |
| Teiji          |
| Temple         |
| Terresa        |
| Teruyuki       |
| Tesuro         |
| Tesuya         |
| Tetsurou       |
| Tetsushi       |
| Teunis         |
| Thanasis       |
| Theirry        |
| Theron         |
| Thodoros       |
| Tianruo        |
| Tiina          |
| Tokuyasu       |
| Tommaso        |
| Tomofumi       |
| Tomokazu       |
| Tomoyuki       |
| Toney          |
| Tonia          |
| Tonny          |
| Toong          |
| Tooru          |
| Torsten        |
| Toshiki        |
| Toshiko        |
| Toshimi        |
| Toshimitsu     |
| Toshimo        |
| Toshimori      |
| Tran           |
| Tremaine       |
| Tristan        |
| Troy           |
| Tru            |
| True           |
| Trygve         |
| Tse            |
| Tsuneo         |
| Tsutomu        |
| Tsvetan        |
| Tsz            |
| Tua            |
| Turgut         |
| Tuval          |
| Tze            |
| Tzu            |
| Tzvetan        |
| Udaiprakash    |
| Udi            |
| Udo            |
| Ugo            |
| Uinam          |
| Ulf            |
| Uli            |
| Ulises         |
| Ult            |
| Uma            |
| Unal           |
| Ung            |
| Uno            |
| Uri            |
| Uriel          |
| Urs            |
| Uta            |
| Ute            |
| Utpal          |
| Utz            |
| Uwe            |
| Uzi            |
| Val            |
| Valdiodio      |
| Valeri         |
| Valery         |
| Valeska        |
| Valter         |
| Van            |
| Vasilii        |
| Vasilis        |
| Vasiliy        |
| Vatsa          |
| Venkatesan     |
| Vesna          |
| Vidar          |
| Vidya          |
| Vincent        |
| Vishu          |
| Vishv          |
| Vishwani       |
| Visit          |
| Vitali         |
| Vitaly         |
| Vivian         |
| Vojin          |
| Volkmar        |
| Vugranam       |
| Waiman         |
| Wanqing        |
| Wayne          |
| Weicheng       |
| Weidon         |
| Weijing        |
| Weiru          |
| Weiwu          |
| Weiye          |
| Weiyi          |
| Werner         |
| Willard        |
| Wilmer         |
| Wojceich       |
| Wonhee         |
| Woody          |
| Wuxu           |
| Xiadong        |
| Xiahua         |
| Xianlong       |
| Xiaobin        |
| Xiaocheng      |
| Xiaoheng       |
| Xiaopeng       |
| Xiaoqiang      |
| Xiaoqiu        |
| Xiaoshan       |
| Xinan          |
| Xinglin        |
| Xinyu          |
| Xiong          |
| Xiping         |
| Xudong         |
| Xuedong        |
| Xuejia         |
| Xuejun         |
| Xumin          |
| Yaghout        |
| Yagil          |
| Yahiko         |
| Yakichi        |
| Yakkov         |
| Yannik         |
| Yannis         |
| Yechezkel      |
| Yechiam        |
| Yefim          |
| Yifei          |
| Yinghua        |
| Yinlin         |
| Yishai         |
| Yishay         |
| Ymte           |
| Yolla          |
| Yongdong       |
| Yonghoan       |
| Yonghong       |
| Yongmao        |
| Yongmin        |
| Yongqiao       |
| Yoshimitsu     |
| Yoshinari      |
| Youjian        |
| Youngkon       |
| Younwoo        |
| Youpyo         |
| Youssef        |
| Yucai          |
| Yucel          |
| Yuchang        |
| Yuguang        |
| Yuichiro       |
| Yunming        |
| Yuping         |
| Yuqun          |
| Yurii          |
| Yurij          |
| Yuriy          |
| Yuuichi        |
| Zdislav        |
| Zejun          |
| Zeljko         |
| Zengping       |
| Zeydy          |
| Zhanqiu        |
| Zhaofang       |
| Zhenbing       |
| Zhenhua        |
| Zhensheng      |
| Zhigen         |
| Zhiguo         |
| Zhilian        |
| Zhiwei         |
| Zhonghua       |
| Zhonghui       |
| Zhongwei       |
| Zijian         |
| Zine           |
| Zissis         |
| Zita           |
| Zito           |
| Ziva           |
| Ziya           |
| Ziyad          |
| Zongyan        |
| Zorica         |
| Zsolt          |
| Zvonko         |
+----------------+
1275 rows in set (0.25 sec) */

#       O'rtacha oylikni AVG() hisoblaganda GROUP BY dan foydalanish
SELECT `emp_no` AS 'Hodim ID',     -- emp_no ustuniga oid har bir  ( 3 )
AVG(`salary`) AS 'Ortacha oylik'   -- salary ustunlari o'rtachasini shu nomda chiqarsin ( 3 )
FROM `salaries`                    -- salaries jadvalidagi  ( 1 )
GROUP BY `Hodim ID`                -- emp_no ustunini guruhlab ( 2 )
# ORDER BY `Ortacha oylik` DESC;   -- oylik ustunini kamayish tartibida saralasin ( 4 )
ORDER BY `Hodim ID`;               -- hodim id  ustunini saralash ( 4 )

SELECT *         -- Barcha ustunlarni tanlab ( 2 )
FROM `salaries`  -- salaries jadvalidan ( 1 )
LIMIT 20;   /*   -- 20 tasini ko'rsatish ( 3 )
+--------+--------+------------+------------+
| emp_no | salary | from_date  | to_date    |
+--------+--------+------------+------------+
|  10001 |  60117 | 1986-06-26 | 1987-06-26 |
|  10001 |  62102 | 1987-06-26 | 1988-06-25 |
|  10001 |  66074 | 1988-06-25 | 1989-06-25 |
|  10001 |  66596 | 1989-06-25 | 1990-06-25 |
|  10001 |  66961 | 1990-06-25 | 1991-06-25 |
|  10001 |  71046 | 1991-06-25 | 1992-06-24 |
|  10001 |  74333 | 1992-06-24 | 1993-06-24 |
|  10001 |  75286 | 1993-06-24 | 1994-06-24 |
|  10001 |  75994 | 1994-06-24 | 1995-06-24 |
|  10001 |  76884 | 1995-06-24 | 1996-06-23 |
|  10001 |  80013 | 1996-06-23 | 1997-06-23 |
|  10001 |  81025 | 1997-06-23 | 1998-06-23 |
|  10001 |  81097 | 1998-06-23 | 1999-06-23 |
|  10001 |  84917 | 1999-06-23 | 2000-06-22 |
|  10001 |  85112 | 2000-06-22 | 2001-06-22 |
|  10001 |  85097 | 2001-06-22 | 2002-06-22 |
|  10001 |  88958 | 2002-06-22 | 9999-01-01 |
|  10002 |  65828 | 1996-08-03 | 1997-08-03 |
|  10002 |  65909 | 1997-08-03 | 1998-08-03 |
|  10002 |  67534 | 1998-08-03 | 1999-08-03 |
+--------+--------+------------+------------+
20 rows in set (0.00 sec)   */

SELECT `emp_no` AS 'Hodim ID',
AVG(`salary`) AS 'Ortacha oylik'
FROM `salaries`
GROUP BY `Hodim ID`
ORDER BY `Hodim ID`
LIMIT 20;   /*
+----------+---------------+
| Hodim ID | Ortacha oylik |
+----------+---------------+
|    10001 |    75388.9412 |
|    10002 |    68854.5000 |
|    10003 |    43030.2857 |
|    10004 |    56512.2500 |
|    10005 |    87275.7692 |
|    10006 |    50514.9167 |
|    10007 |    70826.7143 |
|    10008 |    49307.6667 |
|    10009 |    78284.5556 |
|    10010 |    76723.0000 |
|    10011 |    49782.0000 |
|    10012 |    46902.8000 |
|    10013 |    52431.5882 |
|    10014 |    52990.3333 |
|    10015 |    40000.0000 |
|    10016 |    74995.4000 |
|    10017 |    87064.7000 |
|    10018 |    68640.0625 |
|    10019 |    47007.2500 |
|    10020 |    43278.2000 |
+----------+---------------+
20 rows in set (0.00 sec)   */

#         Hodimlarning MAX() - eng ko'p va MIN() - eng kam olgan oyliklarini chiqarish
# 20 ta hodimning (dastlabki, minimal) oyligi
SELECT DISTINCT `emp_no` AS `id`,
`salary` AS 'oyligi'
FROM `salaries`
ORDER BY `emp_no`
LIMIT 20;   /* natija:
+-------+--------+
| id    | oyligi |
+-------+--------+
| 10001 |  60117 |
| 10001 |  62102 |
| 10001 |  66074 |
| 10001 |  66596 |
| 10001 |  66961 |
| 10001 |  71046 |
| 10001 |  74333 |
| 10001 |  75286 |
| 10001 |  75994 |
| 10001 |  76884 |
| 10001 |  80013 |
| 10001 |  81025 |
| 10001 |  81097 |
| 10001 |  84917 |
| 10001 |  85112 |
| 10001 |  85097 |
| 10001 |  88958 |
| 10002 |  65828 |
| 10002 |  65909 |
| 10002 |  67534 |
+-------+--------+
20 rows in set (0.00 sec)             */

SELECT `emp_no` AS 'id',            -- 3- 'emp_no' ustunini 'id' deb,
MAX(`salary`) AS 'max oylik',       -- 4- har bir `emp_no` qatorlariga oid maximal `salary`ni 'max oylik' deb,
AVG(`salary`) AS 'ortacha oylik',   -- 5- har bir `emp_no` qatorlariga oid o'rtacha `salary`ni 'ortacha oylik' deb,
MIN(`salary`) AS 'min oylik'        -- 6- va har bir `emp_no` qatorlariga oid minimal `salary`ni 'min oylik' deb
FROM `salaries`                     -- 1- salaries jadvalidagi
GROUP BY `emp_no`                   -- 2- emp_no ustunidagi bir xil elementlarni bir guruhga jamlab
ORDER BY `emp_no`                   -- 7- emp_no satrlarini tartiblab
LIMIT 20;    /* natija:             -- 8- 20 tasini chiqarsin
+-------+-----------+---------------+-----------+
| id    | max oylik | ortacha oylik | min oylik |
+-------+-----------+---------------+-----------+
| 10001 |     88958 |    75388.9412 |     60117 |
| 10002 |     72527 |    68854.5000 |     65828 |
| 10003 |     43699 |    43030.2857 |     40006 |
| 10004 |     74057 |    56512.2500 |     40054 |
| 10005 |     94692 |    87275.7692 |     78228 |
| 10006 |     60098 |    50514.9167 |     40000 |
| 10007 |     88070 |    70826.7143 |     56724 |
| 10008 |     52668 |    49307.6667 |     46671 |
| 10009 |     94443 |    78284.5556 |     60929 |
| 10010 |     80324 |    76723.0000 |     72488 |
| 10011 |     56753 |    49782.0000 |     42365 |
| 10012 |     54794 |    46902.8000 |     40000 |
| 10013 |     68901 |    52431.5882 |     40000 |
| 10014 |     60598 |    52990.3333 |     46168 |
| 10015 |     40000 |    40000.0000 |     40000 |
| 10016 |     77935 |    74995.4000 |     70889 |
| 10017 |     99651 |    87064.7000 |     71380 |
| 10018 |     84672 |    68640.0625 |     55881 |
| 10019 |     50032 |    47007.2500 |     44276 |
| 10020 |     47017 |    43278.2000 |     40000 |
+-------+-----------+---------------+-----------+
20 rows in set (0.00 sec)   */

#    Har bir hodimga necha marta oylik oshirilganini ko'rsatish
SELECT `emp_no` AS 'ID',
COUNT(*) AS 'oyliklar oshirilish soni'
FROM `salaries`
GROUP BY `emp_no`
LIMIT 20;   /*
+-------+--------------------------+
| ID    | oyliklar oshirilish soni |
+-------+--------------------------+
| 10001 |                       17 |
| 10002 |                        6 |
| 10003 |                        7 |
| 10004 |                       16 |
| 10005 |                       13 |
| 10006 |                       12 |
| 10007 |                       14 |
| 10008 |                        3 |
| 10009 |                       18 |
| 10010 |                        6 |
| 10011 |                        7 |
| 10012 |                       10 |
| 10013 |                       17 |
| 10014 |                        9 |
| 10015 |                        1 |
| 10016 |                        5 |
| 10017 |                       10 |
| 10018 |                       16 |
| 10019 |                        4 |
| 10020 |                        5 |
+-------+--------------------------+
20 rows in set (0.00 sec)   */

#           HAVING - guruhlangan natijalarni filtrlash
# HAVING - GROUP BY ishlatilsagina ishlatsa bo'ladi.
SELECT `emp_no` AS 'id',
       MAX(`salary`) AS '150 000 dan katta max oyliklar'
FROM `salaries`
GROUP BY `emp_no`
HAVING MAX(`salary`) > 150000;  /*
+--------+---------------------------------+
| id     | 150  000 dan katta max oyliklar |
+--------+---------------------------------+
|  43624 |                          158220 |
|  46439 |                          150345 |
|  47978 |                          155709 |
|  66793 |                          150052 |
|  80823 |                          154459 |
| 109334 |                          155377 |
| 205000 |                          153715 |
| 237542 |                          152687 |
| 238117 |                          152220 |
| 253939 |                          155513 |
| 254466 |                          156286 |
| 266526 |                          152710 |
| 276633 |                          152412 |
| 279776 |                          150740 |
| 493158 |                          154376 |
+--------+---------------------------------+
15 rows in set (2.18 sec)   */

/*                               AMALLAR KETMA-KETLIGI:
1. SELECT                                   - tanlanadigan ustunlar
2. FROM                                     - qaysi jadvaldan
3. WHERE                                    - qaysiki ixtiyoriy shartlar asosida
4. GROUP BY                                 - bir xil qiymatli yozuvlarni bir guruhga olish
    4.1 HAVING  (GROUP BY  bo'lsa ishlaydi) - shu guruhni shartlar asosida filtrlash
5. ORDER BY                                 - ma'lum bir usutun(lar)ni saralash
6. LIMIT                                    - ma'lum bir miqdorda chegaralab chiqarish  */